config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  use_doorkeeper
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
	root to: "static_pages#home"
	
	resources :songs, only: %i[all_songs create destroy confirm index edit_again all_tracks destroy_tracks tracks_index create_tracks]
	resources :searches, only: %i[search_results search_music]
	resources :contact_emails, only: :create
	resources :profile, only: %i[add index update settings]
	# resources :playlists#, only: %i[add_to_favourites create get_playlists, add_song, view]

	get 'music', to: 'react#show', constraints: { subdomain: 'music' }

	get 'privacy', to: 'static_pages#privacy_policy'
	post 'contact_mail', to: 'static_pages#contact_mail'
	get 'contact', to: 'static_pages#contact'
	get 'terms', to: 'static_pages#terms_of_use'
	get 'copyright', to: 'static_pages#copyright_claims'

	get 'add', to: 'profile#add'
	get 'settings', to: 'profile#settings'
	
	post 'search_music', to: 'searches#search_music'
	get 'search_results', to: 'searches#search_results'
	get 'search_db', to: 'searches#search_db'
	
	post 'homepage_search', to: 'songs#homepage_search'
	get 'all_songs', to: 'songs#all_songs'
	post 'edit_again', to: 'songs#edit_again'
	post 'create_tracks', to: 'songs#create_tracks'
	get 'tracks', to: 'songs#all_tracks'
	get 'tracks_index', to: 'songs#tracks_index'
	delete 'tracks/:id', to: 'songs#destroy_tracks'
	post 'attributes', to: 'songs#confirm'

  namespace :playlists do
  	resources :favourites
  	resources :playlists
  	resources :tracks

  	post 'update_playlist', to: 'playlists#update'
  	post 'update_favourites', to: 'favourites#update'
  	post 'update_tracks', to: 'tracks#update'

  	get 'playlists_api', to: 'playlists#index_api'
  	get 'show_api/:id', to: 'playlists#show_api'
  	get 'favourites_api', to: 'favourites#index_api'
  	get 'tracks_api', to: 'tracks#index_api'
  	post 'add_song', to: 'playlists#add_song'
  	# post 'add_song', to: 'playlists#add_song'
  end

  namespace :friends do
  	resources :friends
  	resources :users
  	resources :playlists
  end

  	get 'stonks', to: 'stonks/static_pages#home'
  namespace :stonks do
  	resources :clients

  	get 'about', to: 'static_pages#about' 
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end

	def privacy_policy
	end

	def terms_of_use
	end

	def copyright_claims
	end

	def contact
	end
end

app/controllers/stonks/static_pages_controller.rb
class Stonks::StaticPagesController < ApplicationController

	layout "stonks"

	def home
	end

	def about
	end

end

app/views/static_pages/contact.slim
.container
	= render "layouts/error_messages"
	.columns.is-centered-middle
		.column.is-half

			.is-size-3.p-5.m-5 Contact us
			= form_with url: contact_emails_path, method: :post do |form|
				.field
					.label Name or email
					.control
						= form.text_field :email, class: "input"
				.field
					.label Subject
					.control
						= form.text_field :subject, class: "input"
				.field
					.label Message
					.control
						= form.text_area :message, class: "textarea"
				.field
					.control
						= form.submit :submit, class: "button"

app/views/static_pages/copyright_claims.slim
.container
	.columns.is-centered-middle
		.column.is-8
			.is-size-2.has-text-centered Copyright Claims

			.message.px-5.pt-5.mb-5
				ul
					li We respect the intellectual property rights of others. You may not infringe the copyright, trademark or other proprietary informational rights of any party. We may in our sole discretion remove any Content we have reason to believe violates any of the intellectual property rights of others and may terminate your use of the Website if you submit any such Content.
					li.is-size-5.has-text-weight-bold.mt-2 REPEAT INFRINGER POLICY. AS PART OF OUR REPEAT-INFRINGEMENT POLICY, ANY USER FOR WHOSE MATERIAL WE RECEIVE THREE GOOD-FAITH AND EFFECTIVE COMPLAINTS WITHIN ANY CONTIGUOUS SIX-MONTH PERIOD WILL HAVE HIS GRANT OF USE OF THE WEBSITE TERMINATED.
					li Although we are not subject to United States law, we voluntarily comply with the Digital Millennium Copyright Act. Pursuant to Title 17, Section 512(c)(2) of the United States Code, if you believe that any of your copyrighted material is being infringed on the Website, we have designated an agent to receive notifications of claimed copyright infringement. Notifications should be e-mailed to abuse@mp3juices.cc or sent to:
					.has-text-centered Copyright Agent
					.has-text-centered Harare 
					.has-text-centered Mutare RD.
					.has-text-centered P.O box 0000
					.has-text-centered Zimbabwe
					.has-text-centered Tel: +263778809149
					.has-text-centered email: musicapp@gmail.com
					li.is-size-5.mt-2 All notifications not relevant to us or ineffective under the law will receive no response or action thereupon. An effective notification of claimed infringement must be a written communication to our agent that includes substantially the following:
					ol(type="i")
						li Identification of the copyrighted work that is believed to be infringed. Please describe the work and, where possible, include a copy or the location (e.g., a URL) of an authorized version of the work;
						li Identification of the material that is believed to be infringing and its location or, for search results, identification of the reference or link to material or activity claimed to be infringing. Please describe the material and provide a URL or any other pertinent information that will allow us to locate the material on the Website or on the Internet;
						li Information that will allow us to contact you, including your address, telephone number and, if available, your e-mail address;
						li A statement that you have a good faith belief that the use of the material complained of is not authorized by you, your agent or the law;
						li A statement that the information in the notification is accurate and that under penalty of perjury that you are the owner or are authorized to act on behalf of the owner of the work that is allegedly infringed; and
						li A physical or electronic signature from the copyright holder or an authorized representative.
						
					li.is-size-5.mt-2 If your User Submission or a search result to your website is removed pursuant to a notification of claimed copyright infringement, you may provide us with a counter-notification, which must be a written communication to our above listed agent and satisfactory to us that includes substantially the following:
					ol(type="i")
						li Your physical or electronic signature;
						li Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;
						li A statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled;
						li Your name, address, telephone number, email address and a statement that you consent to the jurisdiction of the courts in the address you provided, Anguilla, and the location(s) in which the purported copyright owner is located; and
						li A statement that you will accept service of process from the purported copyright owner or its agent.

app/views/static_pages/home.slim
/= javascript_pack_tag 'HelloWorld'

.container

	.is-size-2.has-text-centered.p-5.m-5 Welcome to the musicApp!
	.is-centered-middle
		= link_to "Search Now!", search_results_path, class: "button is-centered-middle is-primary", style: "width: 30%;"
	
	.columns.my-3
		.column.is-6.is-offset-3
			.has-text-centered.is-size-4.p-5 Exciting new Features to look forward to:
			.is-centered-middle
				ol.p-2
					li Follow your friends and see what they are listeneng to
					li Discuss music with friends with shared playlists
					li one button to download all the songs on your device 
					li device tracking for multi download to stop duplicates
					li mp3 cutting
					li mp3 header tag change and album art for download
					li Progressive web app to not have to download at all
					li improved automatic renaming
					li in browser player accross tabs
					li lazy load from database
					li search database

			.is-centered-middle
				ul
					li.py-5 please contact us for features you would like to be added
				

app/views/static_pages/privacy_policy.slim
.container
	.columns.is-centered-middle
		.column.is-8
			.is-size-2.has-text-centered Privacy Policy

			.message.px-5.pt-5.mb-5
				ul
					li Pursuant to our Terms of Use, this document describes how we treat personal information related to your use of this website and the services offered on and through it (the „Service”), including information you provide when using it.
					li We expressly and strictly limit use of the Service to adults over 18 years of age or the age of majority in the individual's jurisdiction, whichever is greater. Anyone under this age is strictly forbidden from using the Service. We do not knowingly seek or collect any personal information or data from persons who have not attained this age.


					li.is-size-5.has-text-weight-bold.mt-2 Data Collected
					li We may use your information to provide you with certain features and to create a personalized experience on the Service. We may also use that information to operate, maintain and improve features and functionality of the Service.
					li We use cookies, web beacons and other information to store information so that you will not have to re-enter it on future visits, provide personalized content and information, monitor the effectiveness of the Service and monitor aggregate metrics such as the number of visitors and page views (including for use in monitoring visitors from affiliates). They may also be used to provide targeted advertising based on your country of origin and other personal information.
					li We may aggregate your personal information with personal information of other members and users, and disclose such information to advertisers and other third-parties for marketing and promotional purposes.
					li We may use your information to run promotions, contests, surveys and other features and events.
					li.is-size-5.has-text-weight-bold.mt-2 Disclosures of Information
					li We may be required to release certain data to comply with legal obligations or in order to enforce our Terms of Use and other agreements. We may also release certain data to protect the rights, property or safety of us, our users and others. This includes providing information to other companies or organizations like the police or governmental authorities for the purposes of protection against or prosecution of any illegal activity, whether or not it is identified in the Terms of Use.
					li If you upload, access or transmit any illegal or unauthorized material to or through the Service, or you are suspected of doing such, we may forward all available information to relevant authorities, including respective copyright owners, without any notice to you.
					li.is-size-5.has-text-weight-bold.mt-2 Miscellaneous
					li While we use commercially reasonable physical, managerial and technical safeguards to secure your information, the transmission of information via the Internet is not completely secure and we cannot ensure or warrant the security of any information or content you transmit to us. Any information or content you transmit to us is done at your own risk.